platform:
  provider: unknown

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logscale:
  #values are "none",bootstrap,ui,inputs
  drMode: "none"
  config:
    enableInternalLogger: "true"
    searchPipelineMonitorJob: "true"
  #One of humio,strimzi,external
  kafka:
    manager: "logscale"
    prefixEnable: false
    extraConfigCommon:
      # receive.buffer.bytes=65536 is the default use -1 to set to OS max
      receive.buffer.bytes: -1
      # send.buffer.bytes=131072 is the default use -1 to set to OS max
      send.buffer.bytes: -1

      # Additional external kafka configuration
      # max.partition.fetch.bytes=1048576 is the default value 3 MB should be optimal for logscale
      max.partition.fetch.bytes: 3145728
      # linger.ms with high partition counts and sharding this small delay allows for optimal batch sizing
      # under high loads it will have no effect
      linger.ms: 5

    topics:
      ingest:
        minisr: 2
        retention:
          ms: -1
          bytes: -1
  #kafkaPrefix
  buckets:
    type: none
    prefix: ""

  commonPod:
    podAnnotations: {}
    podLabels: {}
    podSecurityContext:
      runAsUser: 10000
      runAsGroup: 20000
      fsGroup: 20000
      fsGroupChangePolicy: "OnRootMismatch"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 10000
      runAsGroup: 20000
      capabilities:
        drop:
          - ALL

  nodePools:
    - name: api
      replicas: 1
      dataVolumePersistentVolumeClaimSpecTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 468Gi
        storageClassName: gp2
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1
      nodeSelector:
        - kubernetes.io/arch: amd64
      service:
        type: ClusterIP

  replicaCount: 3
  image:
    registry: humio
    repository: humio-core
    tag: 1.184.0
    pullPolicy: IfNotPresent

  digestPartitionsCount: 24

  email: {}
  extraENV:
    - name: MAX_SERIES_LIMIT
      value: "1000"
    - name: ENABLE_IOC_SERVICE
      value: "false"

  jvmARGS:
    ""
    # -server -Xss2m
    # -XX:MaxRAMPercentage=75.0
    # -XX:+UseParallelGC -XX:+UseNUMA
    # -XX:+UseTransparentHugePages
    # -XX:+UnlockDiagnosticVMOptions
    # -XX:CompileCommand=dontinline,com/humio/util/HotspotUtilsJ.dontInline
    # -Xlog:gc+jni=debug:stdout
    # -Xlog:gc*:stdout:time,tags
    # -Dakka.log-config-on-start=on -Dzookeeper.client.secure=false
  enableFeatures:
    {}
    # - FOWARDING
    # - FDR_POLLING_ON_NODE
  dataVolumePersistentVolumeClaimSpecTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1.5Ti
    storageClassName: openebs-lvmpv

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    labels: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: null
  podAnnotations: {}

  service:
    type: ClusterIP
    port: 80
    annotations: {}
    inputs:
      type: ClusterIP
      annotations: {}
    ui:
      type: ClusterIP
      annotations: {}

  ingress:
    api:
      enabled: false
      # className: "ngnix"
      annotations: {}
      tls: false
    ui:
      enabled: false
      # className: "ngnix"
      annotations: {}
      tls: false
    inputs:
      enabled: false
      # className: "ngnix"
      annotations: {}
      tls: false
    inputsES:
      enabled: false
  nodeSelector: {}

  tolerations: []

  affinity: {}

preload:
  image:
    repository: alpine
    tag: 3.21.3
setDynamic:
  enabled: true
  image:
    repository: curlimages/curl
    tag: 8.12.1
setRoot:
  enabled: true
  image:
    repository: curlimages/curl
    tag: 8.12.1
pdfRenderService:
  enabled: true
  replicas: 1
  resources: {}
  extraENV: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - pdfRenderService
          topologyKey: kubernetes.io/hostname
  nodeSelector: {}
  topologySpreadConstraints:
    - maxSkew: 2
      minDomains: 2
      whenUnsatisfiable: DoNotSchedule
      topologyKey: topology.kubernetes.io/zone
      labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
              - pdfRenderService
  tolerations: []
  podSecurityContext:
    {}
    # runAsUser: 10000
    # runAsGroup: 20000
    # fsGroup: 20000
    # fsGroupChangePolicy: "OnRootMismatch"
  containerSecurityContext:
    {}
    # allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 10000
    # runAsGroup: 20000
    # capabilities:
    #   drop:
    #     - ALL
  extraVolumeMounts: []
  extraVolumes: []
  config:
    cleanupInterval: "7d"
    maxConcurrentJobs: "10"
    debug: "false"
    tmpDirSize: "500Mi"
    homeDirSize: "500Mi"
  image:
    repository: humio/pdf-render-service
    tag: 0.0.59--build-98--sha-b2bfadbc14733ce3ae1153d555148ee4f3a64013
    pullPolicy: IfNotPresent
    imagePullSecrets: []
