{{- if .Values.logscale.ingress.ui.enabled -}}
{{- $fullName := include "humio-instance.fullname" . -}}
{{- $svcPort := 8080 -}}
{{- if eq .Values.platform.provider "gcp" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $fullName }}-ui
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 1
    type: HTTP
    requestPath: /api/v1/is-node-up
    port: 8080
---
{{- if eq .Values.logscale.ingress.ui.classNameAnnotation "gce" }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $fullName }}-ui
spec:
  sslPolicy: {{ .Values.logscale.ingress.ui.gcpSSLPolicy | default "logscale-ui"}}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
{{- end }}
{{- end }}
{{- if and .Values.logscale.ingress.ui.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.logscale.ingress.ui.annotations "kubernetes.io/humio.ingress.ui.class") }}
  {{- $_ := set .Values.logscale.ingress.ui.annotations "kubernetes.io/humio.ingress.ui.class" .Values.logscale.ingress.ui.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- if .Values.logscale.ingress.ui.classNameAnnotation }}
    kubernetes.io/ingress.class: {{ .Values.logscale.ingress.ui.classNameAnnotation }}
  {{- end }}
  {{- if eq .Values.platform.provider "gcp" }}
    cloud.google.com/backend-config: '{"default": "{{ $fullName }}-ui"}'
  {{- if eq .Values.logscale.ingress.ui.classNameAnnotation "gce" }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $fullName }}-ui
  {{- end }}  
  {{- end }}

  {{- with .Values.logscale.ingress.ui.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.logscale.ingress.ui.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.logscale.ingress.ui.className }}
  {{- end }}
  {{- if .Values.logscale.ingress.ui.tls }}
  tls:
    - hosts:
        - {{ .Values.logscale.fqdn }}
      {{- if .Values.logscale.ingress.ui.tlsSecretName }}
      secretName: {{- .Values.logscale.ingress.ui.tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.logscale.fqdn }}
      http:
        paths:
        {{- if .Values.scim.enabled }}
          - path: /api/ext/scim/v2
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "humio-instance.fullname" . }}-scim
                port:
                  number: 8080
              {{- else }}
              serviceName: {{ include "humio-instance.fullname" . }}-scim
              servicePort: 8080
              {{- end }}
        {{- end }}
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-http-only
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-http-only
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
