{{- range .Values.logscale.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "humio-instance.fullname" $ }}-{{ .name }}}
  labels:
    {{- include "humio-instance.labels" $ | nindent 4 }}
    {{- with .labels }}  
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .tls }}
  tls:
    - hosts:
        - {{ $.host }}
      {{- with .SecretName }}
      secretName: {{ . }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ $.host }}
      http:
        paths:
        {{- range .endpoints }}        
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "humio-instance.fullname" $ }}-{{ .pool }}
                port:
                  number: {{ .port | default "8080" }}              
        {{- end }}
{{- end }}
