{{- if .Values.humio.ingress.ui.enabled -}}
{{- $fullName := include "humio-instance.fullname" . -}}
{{- $svcPort := 8080 -}}
{{- if eq  .Values.platform "gcp" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $fullName }}-ui
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 1
    type: HTTP
    requestPath: /api/v1/status
    port: 8080
---  
{{- end }}
{{- if and .Values.humio.ingress.ui.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.humio.ingress.ui.annotations "kubernetes.io/humio.ingress.ui.class") }}
  {{- $_ := set .Values.humio.ingress.ui.annotations "kubernetes.io/humio.ingress.ui.class" .Values.humio.ingress.ui.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- if eq .Values.platform "gcp" }}
    cloud.google.com/backend-config: '{"default": "{{ $fullName }}-ui"}'
  {{- end }}

  {{- with .Values.humio.ingress.ui.annotations }}
    {{- toYaml . | nindent 4 }}    
  {{- end }}
spec:
  {{- if and .Values.humio.ingress.ui.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingress.uiClassName: {{ .Values.humio.ingress.ui.className }}
  {{- end }}
  {{- if .Values.humio.ingress.ui.tls }}
  tls:
    - hosts:
        - {{ .Values.humio.fqdn }}
      secretName: {{ $fullName }}-ui-tls
  {{- end }}
  rules:    
    - host: {{ .Values.humio.fqdn }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-http-only
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-http-only
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
