{{- if .Values.logscale.ingress.inputsES.enabled -}}
{{- $fullName := include "humio-instance.fullname" . -}}
{{- $svcPort := 8080 -}}
{{- if eq .Values.platform.provider "gcp" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $fullName }}-inputs
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 1
    type: HTTP
    requestPath: /api/v1/status
    port: 8080
---
{{- if eq .Values.logscale.ingress.inputsES.classNameAnnotation "gce" }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $fullName }}-inputs
spec:
  sslPolicy: {{ .Values.logscale.ingress.inputsES.gcpSSLPolicy | default "logscale-inputs" }}
---
{{- end }}
{{- end }}
{{- if and .Values.logscale.ingress.inputsES.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.logscale.ingress.inputsES.annotations "kubernetes.io/humio.ingress.inputsES.class") }}
  {{- $_ := set .Values.logscale.ingress.inputsES.annotations "kubernetes.io/humio.ingress.inputsES.class" .Values.logscale.ingress.inputsES.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-inputs
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- if .Values.logscale.ingress.inputsES.classNameAnnotation }}
    kubernetes.io/ingress.class: {{ .Values.logscale.ingress.inputsES.classNameAnnotation }}
  {{- end }}
  {{- if eq .Values.platform.provider "gcp" }}
    cloud.google.com/backend-config: '{"default": "{{ $fullName }}-inputs"}'    
  {{- if eq .Values.logscale.ingress.inputsES.classNameAnnotation "gce" }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $fullName }}-inputs
  {{- end }}
  {{- end }}
  {{- with .Values.logscale.ingress.inputsES.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.logscale.ingress.inputsES.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.logscale.ingress.inputsES.className }}
  {{- end }}
  {{- if .Values.logscale.ingress.inputsES.tls }}
  tls:
    - hosts:
        - {{ .Values.logscale.fqdnInputsES }}
      {{- if .Values.logscale.ingress.inputsES.tlsSecretName }}
      secretName: {{- .Values.logscale.ingress.inputsES.tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    - 
      {{- if .Values.logscale.fqdnInputsES }}
      host: {{ .Values.logscale.fqdnInputsES }}
      {{- end }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-ingest-only
                port:
                  number: 9200
              {{- else }}
              serviceName: {{ $fullName }}-ingest-only
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
