{{- if eq .Values.humio.kafka.manager "strimzi" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafka.prefixEnable }}
  name: {{ .Values.humio.kafka.topicPrefix | default .Release.Name }}-global-events
{{ else }}
  name: global-events
{{- end }}
  labels:
    strimzi.io/cluster: {{ include "humio-instance.fullname" . }}
    {{- include "humio-instance.labels" . | nindent 4 }}
spec:
{{- if .Values.humio.kafka.prefixEnable }}
  topicName: {{ .Values.humio.kafka.topicPrefix | default .Release.Name }}-global-events
{{ else }}
  topicName: global-events
{{- end }}
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: "delete"
    compression.type: producer
    min.insync.replicas: 2    
    max.message.bytes: 2097152
    retention.bytes: 1073741824
    retention.ms: -1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafka.prefixEnable }}
  name: {{ .Values.humio.kafka.topicPrefix | default .Release.Name }}-transientchatter-events
{{ else }}
  name: transientchatter-events
{{- end }}
  labels:
    strimzi.io/cluster: {{ include "humio-instance.fullname" . }}
spec:
{{- if .Values.humio.kafka.prefixEnable }}
  topicName: {{ .Values.humio.kafka.topicPrefix | default .Release.Name }}-transientChatter-events
{{ else }}
  topicName: transientChatter-events
{{- end }}
  partitions: 12
  replicas: 3
  config:
    cleanup.policy: "delete"
    compression.type: producer
    min.insync.replicas: 2    
    retention.ms: 3600000
    retention.bytes: -1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafka.prefixEnable }}
  name: {{ .Values.humio.kafka.topicPrefix | default .Release.Name }}-humio-ingest
{{ else }}
  name: humio-ingest
{{- end }}
  labels:
    strimzi.io/cluster: {{ include "humio-instance.fullname" . }}
spec:
{{- if .Values.humio.kafka.prefixEnable }}
  topicName: {{ .Values.humio.kafka.topicPrefix | default .Release.Name }}-humio-ingest
{{ else }}
  topicName: humio-ingest
{{- end }}
  partitions: {{ .Values.humio.digestPartitionsCount }}
  replicas: 3
  config:
    cleanup.policy: "delete"
    compression.type: producer
    min.insync.replicas: {{ .Values.humio.kafka.topics.ingest.minisr }}
    retention.ms: {{ .Values.humio.kafka.topics.ingest.retention.ms }}   
    retention.bytes: {{ .Values.humio.kafka.topics.ingest.retention.bytes }}
    max.message.bytes: 10485760
       
{{- end }}
