{{- if eq .Values.humio.kafka.manager "strimzi" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafka.prefixEnable }}
  name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-global-events
{{ else }}
  name: global-events
{{- end }}
  labels:
    strimzi.io/cluster: {{ .Values.humio.kafka.strimziCluster }}
    {{- include "humio-instance.labels" . | nindent 4 }}
spec:
{{- if .Values.humio.kafka.prefixEnable }}
  topicName: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-global-events
{{ else }}
  topicName: global-events
{{- end }}
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: "compact,delete"
    compression.type: producer
    min.insync.replicas: 2    
    max.message.bytes: 2097152
    retention.bytes: 1073741824
    retention.ms: -1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafka.prefixEnable }}
  name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-transientchatter-events
{{ else }}
  name: transientchatter-events
{{- end }}
  labels:
    strimzi.io/cluster: {{ .Values.humio.kafka.strimziCluster }}
spec:
{{- if .Values.humio.kafka.prefixEnable }}
  topicName: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-transientChatter-events
{{ else }}
  topicName: transientChatter-events
{{- end }}
  partitions: 12
  replicas: 3
  config:
    cleanup.policy: "compact,delete"
    compression.type: producer
    min.insync.replicas: 2    
    retention.ms: 3600000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafka.prefixEnable }}
  name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-humio-ingest
{{ else }}
  name: humio-ingest
{{- end }}
  labels:
    strimzi.io/cluster: {{ .Values.humio.kafka.strimziCluster }}
spec:
{{- if .Values.humio.kafka.prefixEnable }}
  topicName: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-humio-ingest
{{ else }}
  topicName: humio-ingest
{{- end }}
  partitions: 720
  replicas: 2
  config:
    cleanup.policy: "compact,delete"
    compression.type: producer
    min.insync.replicas: 2
    retention.ms: 604800000    
    retention.bytes: 1073741824
    max.message.bytes: 10485760
# ---
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaUser
# metadata:
#   name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-kafka-user
#   labels:
#     strimzi.io/cluster: {{ .Values.humio.kafka.strimziCluster }}
# spec:
#   authentication:
#     type: scram-sha-512
#   authorization:
#     type: simple
#     acls:
#       # Example consumer Acls for topic my-topic using consumer group my-group
#       - resource:
#           type: topic
#         {{- if .Values.humio.kafka.prefixEnable }}
#           name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-global-events
#         {{ else }}
#           name: global-events
#         {{- end }}
#           patternType: literal
#         operations:
#           - Describe
#           - Read
#           - Write
#         host: "*"      
#       - resource:
#           type: topic
#         {{- if .Values.humio.kafka.prefixEnable }}
#           name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-transientChatter-events
#         {{ else }}
#           name: transientChatter-events
#         {{- end }}
#           patternType: literal
#         operations:
#           - Describe
#           - Read
#           - Write
#         host: "*"     
#       - resource:
#           type: topic
#         {{- if .Values.humio.kafka.prefixEnable }}
#           name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-humio-ingest
#         {{ else }}
#           name: humio-ingest
#         {{- end }}
#           patternType: literal
#         operations:
#           - Describe
#           - Read
#           - Write
#         host: "*"                     
{{- end }}
