{{- if .Values.logscale.serviceAccount.create | default true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "humio-instance.logscale.serviceAccountName" . }}
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
    {{- with .Values.logscale.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.logscale.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:{{ include "humio-instance.logscale.serviceAccountName" . }}
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:{{ include "humio-instance.logscale.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:{{ include "humio-instance.logscale.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "humio-instance.logscale.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "humio-instance.logscale.serviceAccountName" . }}
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "humio-instance.logscale.serviceAccountName" . }}
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "humio-instance.logscale.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "humio-instance.logscale.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
