{{- if .Values.otel.components.inject }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "humio-instance.fullname" . }}-java
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}  
spec:
  env:
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
  exporter:
    {{- if .Values.otel.components.app }}
    endpoint: http://{{ include "humio-instance.fullname" . }}-app-collector-headless:4317
    {{- else }}
    endpoint: {{ .Values.otel.components.otlpURI }}
    {{- end }}
  propagators:
    - tracecontext
    - baggage
  # sampler:
  #   type: parentbased_traceidratio
  #   argument: "0.25"
  java:
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: "false"
      - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
        value: "false"
      - name: OTEL_INSTRUMENTATION_RUNTIME_METRICS_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_LOG4J_CONTEXT_DATA_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_LOG4J_APPENDER_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_OSHIENABLED
        value: "true"
{{- end }}                      