---
apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: {{ include "humio-instance.fullname" . }}
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
spec:

  dataVolumePersistentVolumeClaimPolicy: 
    reclaimType: {{ .Values.logscale.dataVolumePersistentVolumeClaimPolicy | default "OnNodeDelete" }}
  dataVolumePersistentVolumeClaimSpecTemplate:
  {{- with .Values.logscale.dataVolumePersistentVolumeClaimSpecTemplate }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

  commonEnvironmentVariables:
  {{- include "humio-instance.environment" . | nindent 2 }}
  {{- include "humio-instance.environmentKafka" . | nindent 2 }}

{{- if eq  .Values.logscale.auth.method  "saml" }}
  idpCertificateSecretName: "{{ include "humio-instance.fullname" . }}-idp-certificate"
{{- end }}
  hostname: {{ .Values.logscale.fqdn }}

{{- if .Values.logscale.helperImage }}  
  helperImage: {{ .Values.logscale.helperImage }}
{{- end }}
  #We use helm to produce ingress so we prevent operator from doing it
  ingress: {}
  license:
    secretKeyRef:
      key: {{ .Values.logscale.existingLicenseSecretNameKey | default "license" }}
      name: {{ .Values.logscale.existingLicenseSecretName }}
  digestPartitionsCount: {{ .Values.logscale.digestPartitionsCount }}
  storagePartitionsCount: 1 # Still required but not used
  targetReplicationFactor: 1
  tls:
    enabled: false

  nodePools:
  {{- include "humio-instance.nodePools" . | nindent 2 }}
