apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "humio-instance.fullname" . }}-setdynamic
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: "setdynamic"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "humio-instance.labels" . | nindent 8 }}    
        app.kubernetes.io/component: "setdynamic"
    spec:
      containers:
        - name: humio-setdynamic
          image: "{{ .Values.setroot.image.repository }}:{{ .Values.setroot.image.tag }}"
          command:
            - sh
            - -c
          args:
            - >
              curl -v -XPOST --max-time 10 --retry 30 --retry-delay 0 --retry-max-time 600 --retry-connrefused 
              -H "Content-Type: application/json"              
              -H "Authorization: Bearer $TOKEN" 
              -d "mutation{
                    setDynamicConfig(input:{config: FlushSegmentsAndGlobalOnShutdown, value: \"$FLUSHONSHUTDOWN\"})
                  }" 
              http://$HUMIOSVC:8080/api/v1/users
          env:
            - name: $FLUSHONSHUTDOWN
{{- if eq .Values.humio.drMode "pre" }}            
              value: "true"
{{- else }}              
              value: "false"
{{- end }}
            - name: HUMIOSVC
              value: {{ include "humio-instance.fullname" . }}-http-only
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "humio-instance.fullname" . }}-admin-token
                  key: token

      restartPolicy: Never
  backoffLimit: 4