apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "humio-instance.fullname" . }}-setdynamic
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: "setdynamic"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "humio-instance.labels" . | nindent 8 }}    
        app.kubernetes.io/component: "setdynamic"
    spec:
      containers:
        - name: humio-setdynamic
          image: "{{ .Values.setroot.image.repository }}:{{ .Values.setroot.image.tag }}"
          command:
            - sh
            - -c
          args:
            - >
            curl "http://$HUMIOSVC:8080/graphql" \
              -H 'accept: application/json, multipart/mixed' \
              -H 'content-type: application/json' \
              --data-raw '{"query":"mutation {\n  setDynamicConfig(\n    input: {config: FlushSegmentsAndGlobalOnShutdown, value: \"$TOKEN\"}\n  )\n}\n"}' \
              --compressed              
          env:
            - name: FLUSHONSHUTDOWN
{{- if eq .Values.humio.drMode "pre" }}            
              value: "true"
{{- else }}              
              value: "false"
{{- end }}
            - name: HUMIOSVC
              value: {{ include "humio-instance.fullname" . }}-http-only
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "humio-instance.fullname" . }}-admin-token
                  key: token
          resources:
              requests:
                  memory: 1Mi
                  cpu: 10m
              limits:
                  memory: 10Mi
                  cpu: 20m
          securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                  drop: ["ALL"]
              runAsNonRoot: true
              readOnlyRootFilesystem: true
              runAsUser: 10001
              runAsGroup:  10001
      restartPolicy: Never
  backoffLimit: 4