{{- if .Values.pdfRenderService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "humio-instance.fullname" . }}-pdfrenderservice
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: "pdfRenderService"
spec:
  replicas: {{ .Values.pdfRenderService.replicas }}
  selector:
    matchLabels:
      {{- include "humio-instance.selectorLabels" . | nindent 6 }}    
      app.kubernetes.io/component: "pdfRenderService"
  template:
    metadata:
      labels:
        {{- include "humio-instance.selectorLabels" . | nindent 8 }}    
        app.kubernetes.io/component: "pdfRenderService"
    spec:
      hostUsers: {{ .Values.pdfRenderService.hostUsers | default true }}      
      {{- with .Values.pdfRenderService.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: pdfrenderservice
        image: "{{ .Values.pdfRenderService.image.repository }}:{{ .Values.pdfRenderService.image.tag }}"
        {{- with .Values.pdfRenderService.resources}}
        resources:
        {{ . | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 5123
        env:
        - name: CLEANUP_INTERVAL
          value: {{ .Values.pdfRenderService.config.cleanupInterval | quote}}
        - name: MAX_CONCURRENT_JOBS
          value: {{ .Values.pdfRenderService.config.maxConcurrentJobs | quote }}
        - name: DEBUG
          value: {{ .Values.pdfRenderService.config.debug | default "false" | quote }}
        {{- with .Values.pdfRenderService.extraENV }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/pptruser
          name: home
        {{- with .Values.pdfRenderService.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.pdfRenderService.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}           
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: {{ .Values.pdfRenderService.config.tmpDirSize | quote }}
      - name: home
        emptyDir:
          sizeLimit: {{ .Values.pdfRenderService.config.homeDirSize | quote }}
      {{- with .Values.pdfRenderService.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.pdfRenderService.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pdfRenderService.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pdfRenderService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pdfRenderService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pdfRenderService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pdfRenderService.topologySpreadConstraints }}
      topologySpreadConstraints:
          {{- toYaml . | nindent 8 }}
      {{- end }}
 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}    
    app.kubernetes.io/component: "pdfRenderService"
  name: {{ include "humio-instance.fullname" . }}-pdfrenderservice
spec:
  ports:
  - name: http
    port: 5123
    protocol: TCP
    targetPort: 5123
  selector:
  
    {{- include "humio-instance.selectorLabels" . | nindent 4 }}    
    app.kubernetes.io/component: "pdfRenderService"
  sessionAffinity: None
  type: ClusterIP
{{- end }}        