{{- if .Values.otel.components.app }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "humio-instance.fullname" . }}-app
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}
  {{- with .Values.otel.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  serviceAccount: {{ include "humio-instance.humio.serviceAccountName" . }}-otel
  image: otel/opentelemetry-collector-contrib:0.56.0
  maxReplicas: 6
  minReplicas: 3
  mode: deployment
  env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: HUMIO_TOKEN_OTEL_LOGS
          valueFrom:
            secretKeyRef:
                name: {{ include "humio-instance.fullname" . }}-all-humio-infra-otel-logs
                key: token
        - name: HUMIO_TOKEN_OTEL_METRICS
          valueFrom:
            secretKeyRef:
                name: {{ include "humio-instance.fullname" . }}-all-humio-infra-otel-metrics
                key: token
        - name: HUMIO_TOKEN_OTEL_TRACE
          valueFrom:
            secretKeyRef:
                name: {{ include "humio-instance.fullname" . }}-all-humio-infra-otel-trace
                key: token
  config: |
    exporters:
        otlphttp/otel_logs:
            endpoint: "http://{{ include "humio-instance.fullname" . }}-ingest-only:8080/api/v1/ingest/otlp"
            headers:
              Authorization: Bearer $HUMIO_TOKEN_OTEL_LOGS
        otlphttp/otel_metrics:
            endpoint: "http://{{ include "humio-instance.fullname" . }}-ingest-only:8080/api/v1/ingest/otlp"
            headers:
              Authorization: Bearer $HUMIO_TOKEN_OTEL_METRICS
        otlphttp/otel_trace:
            endpoint: "http://{{ include "humio-instance.fullname" . }}-ingest-only:8080/api/v1/ingest/otlp"
            headers:
              Authorization: Bearer $HUMIO_TOKEN_OTEL_TRACE
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/otel_metrics]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/otel_logs]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/otel_trace]
  {{- end }}