{{- if eq .Values.humio.kafkaManager "strimzi" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafkaPrefixEnable }}
  name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-global-events
{{ else }}
  name: global-events
{{- end }}
  labels:
    strimzi.io/cluster: {{ .Values.strimziCluster }}
spec:
{{- if .Values.humio.kafkaPrefixEnable }}
  topicName: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-global-events
{{ else }}
  topicName: global-events
{{- end }}
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: "compact,delete"
    compression.type: producer
    min.insync.replicas: 2    
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafkaPrefixEnable }}
  name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-transientchatter-events
{{ else }}
  name: transientchatter-events
{{- end }}
  labels:
    strimzi.io/cluster: {{ .Values.strimziCluster }}
spec:
{{- if .Values.humio.kafkaPrefixEnable }}
  topicName: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-transientChatter-events
{{ else }}
  topicName: transientChatter-events
{{- end }}
  partitions: 12
  replicas: 3
  config:
    cleanup.policy: "compact,delete"
    compression.type: producer
    min.insync.replicas: 2    
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
{{- if .Values.humio.kafkaPrefixEnable }}
  name: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-humio-ingest
{{ else }}
  name: humio-ingest
{{- end }}
  labels:
    strimzi.io/cluster: {{ .Values.strimziCluster }}
spec:
{{- if .Values.humio.kafkaPrefixEnable }}
  topicName: {{ .Values.humio.kafkaPrefix | default .Release.Name }}-humio-ingest
{{ else }}
  topicName: humio-ingest
{{- end }}
  partitions: 720
  replicas: 2
  config:
    cleanup.policy: "compact,delete"
    compression.type: producer
    min.insync.replicas: 2
    retention.ms: 604800000    
    retention.bytes: 1073741824

{{- end }}
