apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "humio-instance.fullname" . }}-setroot
  labels:
    {{- include "humio-instance.labels" . | nindent 4 }}  

spec:
  template:
    spec:
      containers:
        - name: humio-set-root
          image: curlimages/curl:7.83.1
          command:
            - sh
            - -c
          args:
            - >
              curl --connect-timeout 5 --max-time 10 --retry 30 --retry-delay 0 --retry-max-time 600 --retry-connrefused -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d "{\"email\": \"$EMAIL\", \"isRoot\": true}" http://$HUMIOSVC:8080/api/v1/users
          env:
            - name: EMAIL
              value: {{ .Values.humio.rootUser }}
            - name: HUMIOSVC
              value: {{ include "humio-instance.fullname" . }}
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "humio-instance.fullname" . }}-admin-token
                  key: token

      restartPolicy: Never
  backoffLimit: 4