
{{- if empty .Values.existingLicenseSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "humio-instance.fullname" . }}-license"
    
type: Opaque
data:
  license: {{  .Values.humio.license | b64enc | quote }}
{{- end }}